### ISSUE TITLE
Feature Request: clickable headings in pages

### ISSUE THREAD

**Issue by joerdav** [cugu/templum#6]
Currently in the templ docs there are many headings that I can click, then copy the url from the browser to send more contextual links to people, such as https://templ.guide/core-concepts/components#code-only-components

It also shows this is possible when you hover a heading by showing a # symbol.

I find this extremely useful, and would love to see it in templum!

**Comment by cugu** [comment]
Should be easily doable with https://github.com/abhinav/goldmark-anchor. Will check that later.

**Comment by cugu** [comment]
Added in https://github.com/cugu/templum/commit/99cf9e22ec9af288591f140f3b4aa048baf884e2
