### ISSUE TITLE
Inline code blocks that contain HTML are not escaped

### ISSUE THREAD

**Issue by joerdav** [cugu/templum#7]
Under this heading: https://cugu.github.io/templum-example/syntax-and-usage/attributes.html#boolean-attributes

There is a note that contains references to HTML that should render here but the HTML is being rendered raw.

```
:::note
templ is aware that `<hr/>` is a void element, and renders `<hr>` instead.
:::
```

**Comment by cugu** [comment]
Good finding, thanks! 

Once we get into HTML context, markdown is not converted any more. Just found https://github.com/stefanfritsch/goldmark-fences which should enable us to stay in markdown context. Will check that later.

**Comment by cugu** [comment]
Fixed!
